services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: bank_customer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: customer_db
    ports:
      - "5433:5432"
    networks:
      - bank-network
    volumes:
      - db-data-bank-customer:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-customer-services
    ports:
      - "8086:8086"
    depends_on:
      - db
    networks:
      - bank-network
    volumes:
      - app-data:/data
    command: ["./wait-for-it.sh", "db:5432", "--", "java", "-jar", "app.jar"]

networks:
  bank-network:
    driver: bridge

volumes:
  db-data-bank-customer:
    driver: local
  app-data:
    driver: local